apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: nginx
        image: "anilbb/webapp-proxy:latest"
        lifecycle:
          preStop:
            exec:
              command: ["nginx"]
